version: '3.7'

services:
  web:
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
    depends_on:
      - pg
    env_file:
      - .env

  pg:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_USER: railsweb
      POSTGRES_DB: arkade
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data:

